apiVersion: v1
kind: Service
metadata:
  name: my-windows-service
  labels:
    app: windows-restapp
    tier: backend  
spec:
  type: ClusterIP 
  selector: 
    app: windows-restapp 
  ports: 
    - name: http
      port: 8081
      targetPort: 8080