apiVersion: v1
kind: Service
metadata:
  name: replicaset-loadbalancer-service
spec:
  type: LoadBalancer 
  selector: 
    app: sampleapiapp 
  ports: 
    - name: http
      port: 8090
      targetPort: 8080