apiVersion: v1
kind: Service 
metadata:
  name: frontend-loadbalancer-service
  labels:
    app: frontend-webapp
    tier: frontend  
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: frontend-webapp
  ports: 
    - name: http
      port: 8082 # Service Port
      targetPort: 8080 # Container Port